Repository tillersystems/Stardust, pull requests merged in 2018-12, with the labels that each got.

#232 chore(yarn): update @storybook/react to version 4.0.10
  package.json
  yarn.lock
Labels: dependencies update, renovate

#234 chore(yarn): update @storybook/react to version 4.0.11
  package.json
  yarn.lock
Labels: dependencies update, renovate

#233 chore(yarn): update @sambego/storybook-state to version 1.3.2
  package.json
  yarn.lock
Labels: dependencies update, renovate

#235 chore(yarn): update @babel/preset-env to version 7.2.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#236 chore(yarn): update enzyme-to-json to version 3.3.5
  package.json
  yarn.lock
Labels: dependencies update, renovate

#237 feat(file-icon): add file icon to data
  src/Icon/data.js
Labels: enhancement

#238 fix(Checkbox): fix checkbox not updated correctly when using as control…
  src/CheckBox/__stories__/CheckBox.stories.js
  src/CheckBox/__tests__/CheckBox.test.js
  src/CheckBox/__tests__/__snapshots__/CheckBox.test.js.snap
  src/CheckBox/index.js
Labels: bug, enhancement

#239 chore(yarn): update @storybook/react to version 4.0.12
  package.json
  yarn.lock
Labels: dependencies update, need review

#241 chore(yarn): update eslint to version 5.10.0
  package.json
  yarn.lock
Labels: dependencies update, need review

#242 chore(yarn): update enzyme to version 3.8.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#243 chore(yarn): update enzyme-adapter-react-16 to version 1.7.1
  package.json
  yarn.lock
Labels: dependencies update, renovate

#244 chore(yarn): update popmotion to version 8.5.4
  package.json
  yarn.lock
Labels: dependencies update, renovate

#245 chore(yarn): update @nivo/bar to version 0.52.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#246 chore(yarn): update babel-plugin-styled-components to version 1.9.3
  package.json
  yarn.lock
Labels: dependencies update, renovate

#248 chore(yarn): update babel-plugin-styled-components to version 1.9.4
  package.json
  yarn.lock
Labels: dependencies update, renovate

#250 chore(yarn): update @storybook/react to version 4.1.1
  package.json
  yarn.lock
Labels: dependencies update, renovate

#231 test(avatar): refactor unit test with react-testing-library instead o…
  .eslintrc
  internal/jest/index.js
  internal/jest/utils.js
  package.json
  src/Avatar/__tests__/Avatar.test.js
  src/Avatar/__tests__/__snapshots__/Avatar.test.js.snap
  yarn.lock
Labels: enhancement, need review

#276 chore(yarn): update react-testing-library to version 5.3.2
  package.json
  yarn.lock
Labels: dependencies update, renovate

#251 chore(yarn): update husky to version 1.2.1
  package.json
  yarn.lock
Labels: dependencies update, renovate

#278 chore(yarn): update @babel/core to version 7.2.2
  package.json
  yarn.lock
Labels: dependencies update, renovate

#279 chore(yarn): update react-testing-library to version 5.4.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#283 chore(yarn): update @storybook/react to version 4.1.2
  package.json
  yarn.lock
Labels: dependencies update, renovate

#281 chore(yarn): update jest-dom to version 3.0.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#286 test(Logo) use react-testing-library instead of enzyme
  src/Logo/__tests__/Logo.test.js
  src/Logo/__tests__/__snapshots__/Logo.test.js.snap
  src/Logo/index.js
Labels: enhancement, need review

#290 test(Logo) use react-testing-library instead of enzyme
  src/Logo/__tests__/Logo.test.js
Labels: enhancement

#287 test(Value) use react-testing-library instead of enzyme
  src/Value/__tests__/Value.test.js
  src/Value/__tests__/__snapshots__/Value.test.js.snap
Labels: enhancement

#288 chore(yarn): update babel-plugin-styled-components to version 1.10.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#291 test(Icon): use react-testing-library instead of enzyme
  src/Button/__tests__/__snapshots__/Button.test.js.snap
  src/CheckBox/__tests__/__snapshots__/CheckBox.test.js.snap
  src/Date/DatePicker/__tests__/__snapshots__/DatePicker.test.js.snap
  src/Date/DateRangePicker/__tests__/__snapshots__/DateRangePicker.test.js.snap
  src/Dropdown/__tests__/__snapshots__/Dropdown.test.js.snap
  src/Icon/__tests__/Icon.test.js
  src/Icon/__tests__/__snapshots__/Icon.test.js.snap
  src/Icon/index.js
  src/Input/NumberInput/__tests__/__snapshots__/NumberInput.test.js.snap
  src/Input/TextInput/__tests__/__snapshots__/TextInput.test.js.snap
  src/KpiBlock/__tests__/__snapshots__/KpiBlock.test.js.snap
  src/Select/__tests__/__snapshots__/Select.test.js.snap
  src/Table/__tests__/__snapshots__/Table.test.js.snap
Labels: enhancement

#285 test(ButtonGroup): use react-testing-library instead of enzyme
  src/ButtonGroup/__tests__/ButtonGroup.test.js
  src/ButtonGroup/__tests__/__snapshots__/ButtonGroup.test.js.snap
Labels: enhancement

#282 test(Tag): use react-testing-library instead of enzyme
  src/Tag/__tests__/Tag.test.js
  src/Tag/__tests__/__snapshots__/Tag.test.js.snap
  src/Tag/index.js
Labels: enhancement

#284 test(Counter): use react-testing-library instead of enzyme
  src/Counter/__tests__/Increment.test.js
  src/Counter/__tests__/__snapshots__/Increment.test.js.snap
  src/Counter/index.js
Labels: enhancement

#292 test(message): use react-testing-library instead of enzyme
  src/Message/__tests__/Message.test.js
  src/Message/__tests__/__snapshots__/Message.test.js.snap
Labels: enhancement, need review

#280 test(Button): use react-testing-library instead of enzyme
  src/Button/__tests__/Button.test.js
  src/Button/__tests__/__snapshots__/Button.test.js.snap
  src/Button/__tests__/helpers.test.js
  yarn.lock
Labels: enhancement, need review

#296 test(Tooltip): use react-testing-library instead of enzyme
  internal/jest/utils.js
  src/Tooltip/__tests__/Tooltip.test.js
  src/Tooltip/__tests__/__snapshots__/Tooltip.test.js.snap
  src/Tooltip/index.js
Labels: enhancement, need review

#298 refactor(ButtonGroup): check child.type.displayName instead of child.displayName
  src/Button/index.js
  src/ButtonGroup/index.js
  src/Date/DatePicker/__tests__/__snapshots__/DatePicker.test.js.snap
  src/Date/DateRangePicker/__tests__/__snapshots__/DateRangePicker.test.js.snap
  src/Form/__tests__/__snapshots__/Form.test.js.snap
  src/KpiChart/__tests__/__snapshots__/KpiChart.test.js.snap
Labels: enhancement, need review

#303 feat(pin): add new pin component
  src/Pin/README.md
  src/Pin/__stories__/pin.stories.js
  src/Pin/__tests__/Pin.test.js
  src/Pin/__tests__/__snapshots__/Pin.test.js.snap
  src/Pin/index.js
Labels: feature

#294 test(Modal): use react-testing-library instead of enzyme
  src/Modal/Body/__tests__/Body.test.js
  src/Modal/Body/__tests__/__snapshots__/Body.test.js.snap
  src/Modal/Footer/__tests__/Footer.test.js
  src/Modal/Footer/__tests__/__snapshots__/Footer.test.js.snap
  src/Modal/Header/__tests__/Header.test.js
  src/Modal/Header/__tests__/__snapshots__/Header.test.js.snap
  src/Modal/__tests__/Modal.test.js
  src/Modal/__tests__/__snapshots__/Modal.test.js.snap
  src/Modal/index.js
Labels: enhancement, need review

#295 test(Popover): use react-testing-library instead of enzyme
  src/Popover/__tests__/Popover.test.js
  src/Popover/__tests__/__snapshots__/Popover.test.js.snap
  src/Popover/index.js
Labels: enhancement

#297 chore(yarn): update husky to version 1.3.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#299 chore(yarn): update react-testing-library to version 5.4.2
  package.json
  yarn.lock
Labels: dependencies update, renovate

#300 chore(yarn): update react-dom to version 16.7.0
  package.json
  yarn.lock
Labels: dependencies update, need review

#302 chore(yarn): update @babel/preset-env to version 7.2.3
  package.json
  yarn.lock
Labels: dependencies update, renovate

#306 test(ToggleButton): use react-testing-library instead of enzyme
  src/ToggleButton/__tests__/ToggleButton.test.js
  src/ToggleButton/__tests__/__snapshots__/ToggleButton.test.js.snap
  src/ToggleButton/index.js
Labels: enhancement

#305 test(KpiBlock): use react-testing-library instead of enzyme
  src/KpiBlock/__tests__/KpiBlock.test.js
  src/KpiBlock/__tests__/__snapshots__/KpiBlock.test.js.snap
Labels: enhancement

#304 test(Loader): use react-testing-library instead of enzyme
  src/Loader/__tests__/Loader.test.js
  src/Loader/__tests__/__snapshots__/Loader.test.js.snap
  src/Loader/index.js
Labels: enhancement, need review

#307 fix(Pin): export Pin component
  src/index.js
Labels: bug

#309 refactor(Select): refactor Select component
  src/Select/Option/elements.js
  src/Select/Option/index.js
  src/Select/README.md
  src/Select/__stories__/Select.stories.js
  src/Select/__tests__/Select.test.js
  src/Select/__tests__/__snapshots__/Select.test.js.snap
  src/Select/elements.js
  src/Select/index.js
Labels: enhancement

#308 chore(yarn): update @babel/polyfill to version 7.2.5
  package.json
  yarn.lock
Labels: dependencies update, need review, renovate

#310 feat(Icon): add new icons
  src/Icon/data.js
Labels: feature

#311 Test/kpi chart refactor
  src/KpiChart/__tests__/KpiChart.test.js
  src/KpiChart/__tests__/__snapshots__/KpiChart.test.js.snap
  src/KpiChart/index.js
Labels: enhancement

#315 feat(Icons): add new icons
  src/Icon/data.js
Labels: feature

#318 Add custom padding to Modal component
  src/Modal/README.md
  src/Modal/__stories__/Modal.stories.js
  src/Modal/__tests__/Modal.test.js
  src/Modal/elements.js
  src/Modal/index.js
  src/helpers/__tests__/colors.test.js
  src/helpers/colors.js
Labels: enhancement

#316 chore(yarn): update @storybook/react to version 4.1.4
  package.json
  yarn.lock
Labels: dependencies update, renovate

#317 chore(yarn): update eslint to version 5.11.1
  package.json
  yarn.lock
Labels: dependencies update, renovate

#314 Refactor/select
  src/Select/README.md
  src/Select/__stories__/Select.stories.js
  src/Select/__tests__/Select.test.js
  src/Select/__tests__/__snapshots__/Select.test.js.snap
  src/Select/index.js
Labels: feature

#320 test(Modal): fix modal test
  src/Modal/__tests__/Modal.test.js
  src/Modal/__tests__/__snapshots__/Modal.test.js.snap
Labels: enhancement, need review

#323 chore(yarn): update husky to version 1.3.1
  package.json
  yarn.lock
Labels: dependencies update, renovate

#324 chore(yarn): update eslint-plugin-prettier to version 3.0.1
  package.json
  yarn.lock
Labels: dependencies update, renovate

#325 chore(yarn): update popmotion to version 8.5.5
  package.json
  yarn.lock
Labels: dependencies update, renovate
