Repository tillersystems/Stardust, pull requests merged in 2018-11, with the labels that each got.

#184 feat(Tag): create tag component
  .cache/325c8f456729b912b0d2134054eb7448-dfeeb2271cc2857eb0a45a5003c8bbee
  src/Tag/README.md
  src/Tag/__stories__/Tag.stories.js
  src/Tag/__tests__/Tag.test.js
  src/Tag/__tests__/__snapshots__/Tag.test.js.snap
  src/Tag/index.js
  src/index.js
Labels: feature, need review

#191 chore(yarn): update react-dom to version 16.6.1
  package.json
  yarn.lock
Labels: dependencies update, renovate

#195 chore(yarn): update @tillersystems/eslint-config to version 1.1.8
  package.json
  yarn.lock
Labels: dependencies update, renovate

#201 chore(yarn): update enzyme-adapter-react-16 to version 1.7.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#192 refactor(popover): component enhancement
  src/Popover/__tests__/__snapshots__/Popover.test.js.snap
  src/Popover/elements.js
  src/Popover/index.js
Labels: Ready to merge

#193 test(Button): code coverage improvement
  src/Button/__tests__/Button.test.js
  src/Button/__tests__/__snapshots__/Button.test.js.snap
Labels: Ready to merge

#197 test(ToggleButton): improve coverage
  src/ToggleButton/__tests__/ToggleButton.test.js
  src/ToggleButton/__tests__/__snapshots__/ToggleButton.test.js.snap
Labels: Ready to merge

#198 fix(userInfo): remove userInfo
  src/UserInfo/README.md
  src/UserInfo/__stories__/UserInfo.stories.js
  src/UserInfo/__tests__/UserInfo.test.js
  src/UserInfo/__tests__/__snapshots__/UserInfo.test.js.snap
  src/UserInfo/elements.js
  src/UserInfo/index.js
  src/index.js
Labels: Ready to merge

#200 refactor(Tooltip): improve animation
  .cache/325c8f456729b912b0d2134054eb7448-dfeeb2271cc2857eb0a45a5003c8bbee
  src/Date/DateRangePicker/index.js
  src/Form/Field/index.js
  src/Input/NumberInput/index.js
  src/KpiBlock/index.js
  src/Tooltip/index.js
Labels: Ready to merge

#186 feat(Value): create value component
  src/Value/README.md
  src/Value/__stories__/Value.stories.js
  src/Value/__tests__/Value.test.js
  src/Value/__tests__/__snapshots__/Value.test.js.snap
  src/Value/index.js
  src/index.js
Labels: feature

#203 test(value): fix typo
  src/Value/__tests__/Value.test.js
  src/Value/__tests__/__snapshots__/Value.test.js.snap
Labels: enhancement

#204 refactor(Tooltip): make some improve
  .cache/325c8f456729b912b0d2134054eb7448-dfeeb2271cc2857eb0a45a5003c8bbee
  src/Tooltip/__tests__/Tooltip.test.js
  src/Tooltip/__tests__/__snapshots__/Tooltip.test.js.snap
  src/Tooltip/elements.js
  src/Tooltip/index.js
Labels: enhancement

#202 test(modal): improve coverage
  src/Modal/__tests__/Modal.test.js
  src/Modal/__tests__/__snapshots__/Modal.test.js.snap
Labels: enhancement

#205 chore(yarn): update eslint to version 5.9.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#206 chore(yarn): update jest-styled-components to version 6.3.1
  package.json
  yarn.lock
Labels: dependencies update, renovate

#207 chore(yarn): update prettier to version 1.15.2
  package.json
  yarn.lock
Labels: dependencies update, renovate

#208 chore(yarn): update eslint-config-prettier to version 3.3.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#209 chore(yarn): update react-dom to version 16.6.3
  package.json
  yarn.lock
Labels: dependencies update, renovate

#132 feat(Message): create Message component
  .cache/325c8f456729b912b0d2134054eb7448-dfeeb2271cc2857eb0a45a5003c8bbee
  .gitignore
  src/Button/__tests__/__snapshots__/Button.test.js.snap
  src/CheckBox/__tests__/__snapshots__/CheckBox.test.js.snap
  src/Date/DatePicker/__tests__/__snapshots__/DatePicker.test.js.snap
  src/Date/DateRangePicker/__tests__/__snapshots__/DateRangePicker.test.js.snap
  src/Date/DateRangePicker/index.js
  src/Form/Field/index.js
  src/Icon/__tests__/__snapshots__/Icon.test.js.snap
  src/Icon/index.js
  src/Input/NumberInput/__tests__/__snapshots__/NumberInput.test.js.snap
  src/Input/NumberInput/index.js
  src/Input/TextInput/__tests__/__snapshots__/TextInput.test.js.snap
  src/KpiBlock/__tests__/__snapshots__/KpiBlock.test.js.snap
  src/KpiBlock/index.js
  src/Message/README.md
  src/Message/__stories__/Message.stories.js
  src/Message/__tests__/Message.test.js
  src/Message/__tests__/__snapshots__/Message.test.js.snap
  src/Message/constants.js
  src/Message/elements.js
  src/Message/helpers.js
  src/Message/index.js
  src/Select/__tests__/__snapshots__/Select.test.js.snap
  src/index.js
Labels: feature

#185 feat(Table): create Table component
  package.json
  src/Date/DateRangePicker/index.js
  src/Form/Field/index.js
  src/Input/NumberInput/index.js
  src/KpiBlock/index.js
  src/Table/README.md
  src/Table/__stories__/Table.stories.js
  src/Table/__tests__/Table.test.js
  src/Table/__tests__/__snapshots__/Table.test.js.snap
  src/Table/elements.js
  src/Table/index.js
  src/index.js
Labels: feature

#217 chore(yarn): update popmotion to version 8.5.2
  package.json
  yarn.lock
Labels: dependencies update, renovate

#219 chore(yarn): update @nivo/bar to version 0.51.5
  package.json
  yarn.lock
Labels: dependencies update, need review

#221 chore(yarn): update husky to version 1.2.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#223 feat(ButtonGroup): create button group component
  package.json
  src/ButtonGroup/README.md
  src/ButtonGroup/__stories__/ButtonGroup.stories.js
  src/ButtonGroup/__tests__/ButtonGroup.test.js
  src/ButtonGroup/__tests__/__snapshots__/ButtonGroup.test.js.snap
  src/ButtonGroup/index.js
  src/index.js
Labels: feature, need review

#225 chore(yarn): update @storybook/react to version 4.0.9
  package.json
  yarn.lock
Labels: dependencies update, renovate

#228 chore(yarn): update @nivo/bar to version 0.51.6
  package.json
  yarn.lock
Labels: dependencies update, need review

#224 fix(Table): fix desc / asc order
  package.json
  src/Table/index.js
  src/helpers/__tests__/compare.test.js
  src/helpers/compare.js
  yarn.lock
Labels: bug, enhancement

#230 chore(yarn): update prettier to version 1.15.3
  package.json
  yarn.lock
Labels: dependencies update, renovate
