Repository tillersystems/Stardust, pull requests merged in 2019-01, with the labels that each got.

#326 chore(yarn): update eslint-plugin-react to version 7.12.1
  package.json
  src/CheckBox/README.md
  src/CheckBox/index.js
  yarn.lock
Labels: dependencies update, need review, renovate

#327 test(Input): use react-testing-library instead of enzyme
  src/Button/__tests__/__snapshots__/Button.test.js.snap
  src/Button/__tests__/__snapshots__/helpers.test.js.snap
  src/CheckBox/__tests__/__snapshots__/CheckBox.test.js.snap
  src/Date/DatePicker/__tests__/__snapshots__/DatePicker.test.js.snap
  src/Date/DateRangePicker/__tests__/__snapshots__/DateRangePicker.test.js.snap
  src/Form/__tests__/__snapshots__/Form.test.js.snap
  src/Icon/__tests__/__snapshots__/Icon.test.js.snap
  src/Input/NumberInput/__tests__/NumberInput.test.js
  src/Input/NumberInput/__tests__/__snapshots__/NumberInput.test.js.snap
  src/Input/Status/__tests__/__snapshots__/status.test.js.snap
  src/Input/Status/__tests__/status.test.js
  src/Input/Status/index.js
  src/Input/TextInput/__tests__/TextInput.test.js
  src/Input/TextInput/__tests__/__snapshots__/TextInput.test.js.snap
  src/Input/TextInput/index.js
  src/KpiBlock/__tests__/__snapshots__/KpiBlock.test.js.snap
  src/Loader/__tests__/__snapshots__/Loader.test.js.snap
  src/Message/__tests__/__snapshots__/Message.test.js.snap
  src/Table/__tests__/__snapshots__/Table.test.js.snap
  src/Theme/palette.js
Labels: enhancement

#329 feat(Theme): create a story which lists all color palette
  src/Theme/README.md
  src/Theme/__stories__/palette.stories.js
Labels: feature

#330 refactor(Dropdown): add data-testid to to facilitate the test in othe…
  src/Dropdown/__tests__/__snapshots__/Dropdown.test.js.snap
  src/Dropdown/index.js
Labels: enhancement

#328 chore(yarn): update eslint-plugin-react to version 7.12.2
  package.json
  yarn.lock
Labels: dependencies update, renovate

#331 chore(yarn): update babel-loader to version 8.0.5
  package.json
  yarn.lock
Labels: dependencies update, need review, renovate

#333 chore(yarn): update react-testing-library to version 5.4.4
  package.json
  yarn.lock
Labels: dependencies update, renovate

#334 chore(yarn): update eslint to version 5.12.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#335 chore(yarn): update eslint-plugin-react to version 7.12.3
  package.json
  yarn.lock
Labels: dependencies update, renovate

#339 fix(Button): fix button size
  src/Button/__tests__/Button.test.js
  src/Button/__tests__/__snapshots__/Button.test.js.snap
  src/Button/__tests__/__snapshots__/helpers.test.js.snap
  src/Button/elements.js
  src/Button/helpers.js
  src/ButtonGroup/__tests__/__snapshots__/ButtonGroup.test.js.snap
  src/Counter/__tests__/__snapshots__/Increment.test.js.snap
  src/Date/DatePicker/__tests__/__snapshots__/DatePicker.test.js.snap
  src/Date/DateRangePicker/__tests__/__snapshots__/DateRangePicker.test.js.snap
  src/Form/__tests__/__snapshots__/Form.test.js.snap
  src/KpiChart/__tests__/__snapshots__/KpiChart.test.js.snap
Labels: bug, need review

#341 chore(deps): update dependency storybook-readme to v4.0.5
  package.json
  yarn.lock
Labels: dependencies update, need review, renovate

#342 chore(deps): update dependency eslint-config-prettier to v3.4.0
  package.json
  yarn.lock
Labels: dependencies update, need review, renovate

#345 New icon added for Icon component
  src/Icon/__stories__/Icon.stories.js
  src/Icon/data.js
Labels: Ready to merge, enhancement

#344 chore(deps): update dependency pretty-quick to v1.9.0
  package.json
  yarn.lock
Labels: dependencies update, need review, renovate

#346 chore(deps): update dependency eslint-config-prettier to v3.5.0
  package.json
  yarn.lock
Labels: dependencies update, need review, renovate

#347 chore(deps): update dependency eslint-plugin-react to v7.12.4
  package.json
  yarn.lock
Labels: dependencies update, need review, renovate

#349 chore(deps): update dependency popmotion to v8.6.0
  package.json
  yarn.lock
Labels: dependencies update, need review, renovate

#348 fix(tools): fix wrong url to changelog
  internal/tools/release.sh
Labels: Ready to merge, bug

#350 chore(deps): update storybook monorepo to v4.1.7
  package.json
  yarn.lock
Labels: dependencies update, renovate

#352 fix(Icon): fix svg path for zap icon
  src/Icon/data.js
Labels: Ready to merge, bug

#351 chore(deps): update dependency pretty-quick to v1.10.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#353 chore(deps): update dependency eslint to v5.12.1
  package.json
  yarn.lock
Labels: dependencies update, renovate

#354 chore(deps): update dependency eslint-config-prettier to v3.6.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#355 chore(deps): update dependency prettier to v1.16.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#343 test(Date): use react-testing-library instead of enzyme
  src/Date/DatePicker/__tests__/DatePicker.test.js
  src/Date/DatePicker/__tests__/__snapshots__/DatePicker.test.js.snap
  src/Date/DatePicker/index.js
  src/Date/DateRangePicker/__tests__/DateRangePicker.test.js
  src/Date/DateRangePicker/__tests__/__snapshots__/DateRangePicker.test.js.snap
  src/Date/DateRangePicker/index.js
  src/Date/Day/__tests__/Day.test.js
  src/Date/Day/__tests__/__snapshots__/Day.test.js.snap
  src/Date/WeekdayNames/__tests__/WeekdayNames.test.js
  src/Date/WeekdayNames/__tests__/__snapshots__/WeekdayNames.test.js.snap
  src/Date/WeekdayNames/index.js
  src/Date/Weeks/__tests__/Week.test.js
  src/Date/Weeks/__tests__/__snapshots__/Week.test.js.snap
Labels: enhancement, need review

#357 refactor(KpiChart): move out internal parts of the component in their own components
  src/KpiChart/Body/__tests__/Body.test.js
  src/KpiChart/Body/__tests__/__snapshots__/Body.test.js.snap
  src/KpiChart/Body/index.js
  src/KpiChart/Footer/__tests__/Footer.test.js
  src/KpiChart/Footer/__tests__/__snapshots__/Footer.test.js.snap
  src/KpiChart/Footer/index.js
  src/KpiChart/Header/__tests__/Header.test.js
  src/KpiChart/Header/__tests__/__snapshots__/Header.test.js.snap
  src/KpiChart/Header/index.js
  src/KpiChart/__stories__/KpiChart.stories.js
  src/KpiChart/__tests__/KpiChart.test.js
  src/KpiChart/__tests__/__snapshots__/KpiChart.test.js.snap
  src/KpiChart/elements.js
  src/KpiChart/index.js
Labels: enhancement

#356 chore(deps): update babel monorepo
  package.json
  yarn.lock
Labels: dependencies update, renovate

#358 chore(deps): update dependency eslint-plugin-import to v2.15.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#359 chore(deps): update dependency prettier to v1.16.1
  package.json
  yarn.lock
Labels: dependencies update, renovate

#361 chore(deps): update storybook monorepo to v4.1.9
  package.json
  yarn.lock
Labels: dependencies update, renovate

#362 chore(deps): update dependency popmotion to v8.6.1
  package.json
  yarn.lock
Labels: dependencies update, renovate

#363 chore(deps): update dependency @nivo/bar to v0.52.1
  package.json
  yarn.lock
Labels: dependencies update, renovate

#360 feat(Tooltip): Add a props to switch tooltip's appearance
  src/Button/helpers.js
  src/Tooltip/README.md
  src/Tooltip/__stories__/Tooltip.stories.js
  src/Tooltip/__tests__/Tooltip.test.js
  src/Tooltip/__tests__/__snapshots__/Tooltip.test.js.snap
  src/Tooltip/elements.js
  src/Tooltip/helpers.js
  src/Tooltip/index.js
Labels: enhancement

#366 chore(deps): update dependency enzyme-adapter-react-16 to v1.8.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#367 chore(deps): update dependency eslint-plugin-jsx-a11y to v6.2.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#368 fix(Tooltip): Add a border to the pseudo-element ::before
  src/Tooltip/__tests__/Tooltip.test.js
  src/Tooltip/elements.js
  src/Tooltip/helpers.js
Labels: bug, need review

#372 chore(deps): update dependency popmotion to v8.6.2
  package.json
  yarn.lock
Labels: dependencies update, renovate

#369 chore(deps): update jest monorepo to v24 (major)
  package.json
  src/Table/__tests__/__snapshots__/Table.test.js.snap
  yarn.lock
Labels: dependencies update, renovate

#373 feat(Select): add possibility to render other than string in option
  src/Select/Option/index.js
  src/Select/README.md
  src/Select/__stories__/Select.stories.js
  src/Select/__tests__/Select.test.js
  src/Select/index.js
Labels: enhancement, need review

#375 chore(deps): update dependency eslint-plugin-import to v2.16.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#377 chore(deps): update dependency prettier to v1.16.2
  package.json
  yarn.lock
Labels: dependencies update, renovate

#376 fix(Select): add width prop to Select component
  src/Select/README.md
  src/Select/__stories__/Select.stories.js
  src/Select/__tests__/Select.test.js
  src/Select/__tests__/__snapshots__/Select.test.js.snap
  src/Select/index.js
Labels: enhancement, need review

#374 feat(Flag): add new Flag component
  src/Flag/README.md
  src/Flag/__stories__/Flag.stories.js
  src/Flag/__tests__/Flag.test.js
  src/Flag/__tests__/__snapshots__/Flag.test.js.snap
  src/Flag/data.js
  src/Flag/elements.js
  src/Flag/index.js
  src/Form/README.md
  src/Icon/README.md
  src/Input/NumberInput/__tests__/__snapshots__/NumberInput.test.js.snap
  src/Input/README.md
  src/KpiChart/README.md
  src/Modal/README.md
  src/Popover/README.md
  src/index.js
Labels: feature

#380 fix(Form/Field): fix className prop
  src/Form/Field/index.js
  src/Form/__tests__/__snapshots__/Form.test.js.snap
Labels: bug

#379 chore(deps): update dependency prettier to v1.16.3
  package.json
  yarn.lock
Labels: dependencies update, renovate
