Repository tillersystems/Stardust, pull requests merged in 2019-10, with the labels that each got.

#774 fix(Notification): provide time-sensitive information without affecti…
  src/Notification/Container.js
Labels: enhancement, need review

#799 chore(deps): update react to the latest version
  package.json
  src/ButtonGroup/__tests__/ButtonGroup.test.js
  src/Notification/__tests__/provider.test.js
  yarn.lock
Labels: enhancement

#783 feat(TableVirtualized): use react-virtualized components to create new table
  package.json
  src/TableVirtualized/README.md
  src/TableVirtualized/__stories__/TableVirtualized.stories.js
  src/TableVirtualized/__tests__/TableVirtualized.test.js
  src/TableVirtualized/elements.js
  src/TableVirtualized/index.js
  src/index.js
  yarn.lock
Labels: feature

#805 chore: downgrade dom-helpers version to match react-virtualized one
  package.json
  src/TableVirtualized/index.js
  yarn.lock
Labels: bug

#807 fix: update style of Checkbox, Dropdown, Select
  src/CheckBox/index.js
  src/Dropdown/__stories__/Dropdown.stories.js
  src/Dropdown/index.js
  src/Select/elements.js
  src/Select/index.js
Labels: bug

#802 refactor(Modal): replace react-pose by framer-motion for the animation
  package.json
  src/Modal/Footer/__tests__/Footer.test.js
  src/Modal/animation.js
  src/Modal/elements.js
  src/Modal/index.js
  yarn.lock
Labels: enhancement, need review

#824 fix: update css of some Dropdown, Select and Tag
  src/Dropdown/__tests__/__snapshots__/Dropdown.test.js.snap
  src/Dropdown/elements.js
  src/Select/__tests__/__snapshots__/Select.test.js.snap
  src/Select/elements.js
  src/Tag/__tests__/__snapshots__/Tag.test.js.snap
  src/Tag/index.js
Labels: enhancement

#826 fix(Table): fix sticky for safari/ios
  src/Table/elements.js
Labels: bug

#823 refactor(Popover): replace react-pose by framer-motion for the animation
  package.json
  src/Dropdown/__tests__/Dropdown.test.js
  src/Dropdown/animation.js
  src/Dropdown/index.js
  src/Dropdown/utils.js
  src/Popover/__tests__/Popover.test.js
  src/Popover/animation.js
  src/Popover/elements.js
  src/Popover/index.js
  src/Select/__stories__/Select.stories.js
  src/Select/__tests__/Select.test.js
  src/Select/animation.js
  src/Select/index.js
  src/Select/utils.js
  yarn.lock
Labels: enhancement, need review

#838 fix(Table): Fix first header cell height
  src/Table/elements.js
Labels: enhancement

#839 fix(Input): fix input error status alignment
  src/Input/Status/__tests__/__snapshots__/status.test.js.snap
  src/Input/Status/index.js
  src/Input/TextInput/__tests__/__snapshots__/TextInput.test.js.snap
Labels: bug, need review

#840 fix(Table): Change hover cell to hover row
  src/Table/__stories__/Table.stories.js
  src/Table/__tests__/Table.test.js
  src/Table/elements.js
  src/Table/index.js
Labels: enhancement, need review

#845 feat(Select): add customizable displayed value
  src/Select/README.md
  src/Select/__stories__/Select.stories.js
  src/Select/__tests__/Select.test.js
  src/Select/index.js
Labels: feature

#736 feat(Table): Add dropdown row
  src/Table/README.md
  src/Table/__stories__/Table.stories.js
  src/Table/__tests__/Table.test.js
  src/Table/elements.js
  src/Table/index.js
Labels: feature, need review
