Repository tillersystems/Stardust, pull requests merged in 2019-03, with the labels that each got.

#421 chore(deps): update dependency react-testing-library to v6
  package.json
  yarn.lock
Labels: dependencies update, renovate

#422 chore(deps): update babel monorepo to v7.3.4
  package.json
  yarn.lock
Labels: dependencies update, renovate

#424 chore(deps): update dependency eslint-config-prettier to v4.1.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#425 chore(deps): update dependency polished to v3.0.2
  package.json
  yarn.lock
Labels: dependencies update, renovate

#429 feat(Icon): add speech icon
  src/Icon/data.js
Labels: feature

#426 chore(deps): update dependency eslint to v5.15.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#427 chore(deps): update dependency polished to v3.0.3
  package.json
  yarn.lock
Labels: dependencies update, renovate

#428 fix(KpiChart): update Title style
  src/KpiChart/elements.js
  src/KpiChart/index.js
Labels: enhancement

#430 fix(Modal): Fix a bug that makes the modal not center well in safari
  src/Modal/elements.js
Labels: bug, need review

#431 fix: security vulnerabilities in dependencies
  package.json
  yarn.lock
Labels: bug

#432 chore(deps): update storybook to v5
  .storybook/config.js
  package.json
  yarn.lock
Labels: dependencies update

#433 fix(Button): udpate padding values
  src/Button/__tests__/Button.test.js
  src/Button/__tests__/__snapshots__/Button.test.js.snap
  src/Button/__tests__/__snapshots__/helpers.test.js.snap
  src/Button/elements.js
  src/Button/helpers.js
  src/ButtonGroup/__tests__/__snapshots__/ButtonGroup.test.js.snap
  src/Counter/__stories__/Counter.stories.js
  src/Counter/__tests__/__snapshots__/Increment.test.js.snap
  src/Date/DatePicker/__tests__/__snapshots__/DatePicker.test.js.snap
  src/Date/DateRangePicker/__tests__/__snapshots__/DateRangePicker.test.js.snap
  src/Form/__tests__/__snapshots__/Form.test.js.snap
Labels: enhancement

#434 chore(deps): update dependency enzyme-adapter-react-16 to v1.11.2
  package.json
  yarn.lock
Labels: dependencies update, renovate

#435 chore(deps): update dependency eslint to v5.15.1
  package.json
  yarn.lock
Labels: dependencies update, renovate

#436 chore(ci): Fix circleci nodejs image version to 11.10.1
  .circleci/config.yml
Labels: enhancement

#437 chore(deps): update dependency jest-dom to v3.1.3
  package.json
  yarn.lock
Labels: dependencies update, renovate

#438 chore(deps): update dependency popmotion to v8.6.4
  package.json
  yarn.lock
Labels: dependencies update, renovate

#439 chore(deps): update jest monorepo to v24.5.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#441 fix(DatePicker): allow interval in defaultValue
  package.json
  src/DatePicker/Header/__tests__/__snapshots__/Header.test.js.snap
  src/DatePicker/Header/index.js
  src/DatePicker/Weeks/index.js
  src/DatePicker/__stories__/DatePicker.stories.js
  src/DatePicker/__tests__/__snapshots__/DatePicker.test.js.snap
  src/DatePicker/__tests__/__snapshots__/helpers.test.js.snap
  src/DatePicker/__tests__/helpers.test.js
  src/DatePicker/helpers.js
  src/DatePicker/index.js
  src/Input/DatePickerInput/__tests__/DatePickerInput.test.js
  yarn.lock
Labels: bug, need review
