Repository tillersystems/Stardust, pull requests merged in 2019-07, with the labels that each got.

#615 feat(Dropdown): Add portal to Dropdown component
  src/Dropdown/elements.js
  src/Dropdown/index.js
Labels: feature

#624 chore(deps): update babel deps
  package.json
  yarn.lock
Labels: dependencies update

#618 fix(RadioGroup): add callback on value update
  src/RadioButton/index.js
  src/RadioGroup/__stories__/RadioGroup.stories.js
  src/RadioGroup/__tests__/RadioGroup.test.js
  src/RadioGroup/index.js
Labels: bug

#628 fix(Dropdown): put empty array to filtered items when searchable is false
  src/Dropdown/index.js
Labels: need review

#627 chore(babel): specify corejs number in babelrc
  .storybook/.babelrc
Labels: bug, need review

#632 refactor(Dropdown): remove internal style of padding
  .babelrc
  .storybook/.babelrc
  src/Button/__tests__/Button.test.js
  src/Button/__tests__/__snapshots__/helpers.test.js.snap
  src/DatePicker/Header/__tests__/__snapshots__/Header.test.js.snap
  src/DatePicker/__tests__/__snapshots__/DatePicker.test.js.snap
  src/Dropdown/README.md
  src/Dropdown/__stories__/Dropdown.stories.js
  src/Dropdown/__tests__/Dropdown.test.js
  src/Dropdown/__tests__/__snapshots__/Dropdown.test.js.snap
  src/Dropdown/elements.js
  src/Dropdown/index.js
  src/Form/__tests__/__snapshots__/Form.test.js.snap
  src/RadioButton/__tests__/__snapshots__/RadioButton.test.js.snap
  src/RadioGroup/__tests__/__snapshots__/RadioGroup.test.js.snap
  src/Select/__tests__/__snapshots__/Select.test.js.snap
Labels: need review

#640 refactor(Popover): wrap popover with portal and popper.js
  package.json
  src/EventListener/__tests__/EventListener.test.js
  src/EventListener/index.js
  src/Input/DatePickerInput/README.md
  src/Input/DatePickerInput/__tests__/DatePickerInput.test.js
  src/Input/DatePickerInput/__tests__/__snapshots__/DatePickerInput.test.js.snap
  src/Input/DatePickerInput/index.js
  src/Popover/README.md
  src/Popover/__stories__/Popover.stories.js
  src/Popover/__tests__/Popover.test.js
  src/Popover/__tests__/__snapshots__/Popover.test.js.snap
  src/Popover/elements.js
  src/Popover/index.js
  src/ScrollBox/elements.js
  src/ScrollBox/index.js
  src/index.js
  yarn.lock
Labels: enhancement, need review

#641 feat(Notification): create notification component
  src/Notification/Container.js
  src/Notification/README.md
  src/Notification/__stories__/Notifications.stories.js
  src/Notification/__tests__/Container.test.js
  src/Notification/__tests__/__snapshots__/helpers.test.js.snap
  src/Notification/__tests__/__snapshots__/reducer.test.js.snap
  src/Notification/__tests__/helpers.test.js
  src/Notification/__tests__/provider.test.js
  src/Notification/__tests__/reducer.test.js
  src/Notification/constants.js
  src/Notification/elements.js
  src/Notification/helpers.js
  src/Notification/index.js
  src/Notification/provider.js
  src/Notification/reducer.js
  src/index.js
Labels: feature, need review, question

#649 refactor: use Popover to wrap Select and Dropdown components
  src/Dropdown/README.md
  src/Dropdown/__stories__/Dropdown.stories.js
  src/Dropdown/__tests__/Dropdown.test.js
  src/Dropdown/__tests__/__snapshots__/Dropdown.test.js.snap
  src/Dropdown/elements.js
  src/Dropdown/index.js
  src/Input/DatePickerInput/__tests__/__snapshots__/DatePickerInput.test.js.snap
  src/Popover/__stories__/Popover.stories.js
  src/Popover/__tests__/__snapshots__/Popover.test.js.snap
  src/Popover/elements.js
  src/Popover/index.js
  src/Select/README.md
  src/Select/__stories__/Select.stories.js
  src/Select/__tests__/Select.test.js
  src/Select/__tests__/__snapshots__/Select.test.js.snap
  src/Select/elements.js
  src/Select/index.js
Labels: enhancement

#651 test: mock document.createRange
  internal/jest/index.js
Labels: bug, need review

#652 feat(Logo): optimize component for better accessibility
  src/Logo/README.md
  src/Logo/__tests__/Logo.test.js
  src/Logo/__tests__/__snapshots__/Logo.test.js.snap
  src/Logo/index.js
Labels: feature, need review

#642 feat(Icon): optimize component for better accessibility
  .storybook/config.js
  package.json
  src/Button/__tests__/__snapshots__/Button.test.js.snap
  src/CheckBox/__tests__/__snapshots__/CheckBox.test.js.snap
  src/DatePicker/Header/__tests__/__snapshots__/Header.test.js.snap
  src/DatePicker/__tests__/__snapshots__/DatePicker.test.js.snap
  src/Icon/README.md
  src/Icon/__stories__/Icon.stories.js
  src/Icon/__tests__/Icon.test.js
  src/Icon/__tests__/__snapshots__/Icon.test.js.snap
  src/Icon/elements.js
  src/Icon/index.js
  src/Input/NumberInput/__tests__/__snapshots__/NumberInput.test.js.snap
  src/Input/Status/__tests__/__snapshots__/status.test.js.snap
  src/Input/Status/index.js
  src/Input/TextInput/__tests__/__snapshots__/TextInput.test.js.snap
  src/KpiBlock/__tests__/__snapshots__/KpiBlock.test.js.snap
  src/Message/__tests__/Message.test.js
  src/Message/__tests__/__snapshots__/Message.test.js.snap
  src/Message/index.js
  src/Variation/__tests__/__snapshots__/Variation.test.js.snap
  yarn.lock
Labels: feature, need review

#653 fix(Popover): make Portal optional, adjust style, raise refs to parents
  src/Dropdown/index.js
  src/Popover/index.js
  src/Select/index.js
Labels: need review

#655 fix(Radios): add className to custom with styled-components
  src/RadioButton/index.js
  src/RadioGroup/index.js
Labels: need review

#660 fix(Dropdown): retrieve both state and props for displayMenu to trigger rerender
  src/Dropdown/index.js
Labels: bug

#661 fix(Select): allow percentage values for width
  src/Select/index.js
Labels: bug

#664 fix(Popover): retrieve isOpen to trigger rerender
  src/Popover/index.js
Labels: bug

#665 fix: remove border and radius of menu that are now in the parent
  src/Dropdown/elements.js
  src/Select/elements.js
Labels: need review
