Repository tillersystems/Stardust, pull requests merged in 2019-11, with the labels that each got.

#865 fix(Table): update css
  src/Table/elements.js
  src/Table/index.js
Labels: need review

#850 feat(Table): Change column width to match style guidelines
  src/Table/elements.js
  src/Table/index.js
Labels: feature, need review

#869 fix(Table): mobile version + scroll issue
  src/Table/elements.js
  src/Table/index.js
Labels: bug

#849 feat(List): add List component
  src/List/Item/__tests__/Item.test.js
  src/List/Item/elements.js
  src/List/Item/index.js
  src/List/README.md
  src/List/__stories__/List.stories.js
  src/List/__tests__/List.test.js
  src/List/elements.js
  src/List/index.js
  src/helpers/__tests__/formatting.test.js
  src/helpers/formatting.js
  src/helpers/index.js
  src/index.js
Labels: feature

#893 fix(Table): handle shadow rendering when adding/removing columns
  src/Table/index.js
Labels: need review

#898 refacto(Table): split component to improve perfs + fix sort on add/remove columns
  src/Table/TableBody.js
  src/Table/TableFooter.js
  src/Table/TableHeader.js
  src/Table/__stories__/Table.stories.js
  src/Table/elements.js
  src/Table/index.js
Labels: enhancement, need review
