Repository tillersystems/Stardust, pull requests merged in 2019-04, with the labels that each got.

#456 fix(Checkbox): remove shadow on mobile device
  src/CheckBox/__stories__/CheckBox.stories.js
  src/CheckBox/__tests__/CheckBox.test.js
  src/CheckBox/__tests__/__snapshots__/CheckBox.test.js.snap
  src/CheckBox/elements.js
  src/CheckBox/index.js
  src/DatePicker/__tests__/DatePicker.test.js
  src/DatePicker/__tests__/__snapshots__/DatePicker.test.js.snap
  src/Form/__tests__/__snapshots__/Form.test.js.snap
  src/Input/DatePickerInput/__tests__/__snapshots__/DatePickerInput.test.js.snap
  src/Input/NumberInput/__tests__/NumberInput.test.js
  src/Input/NumberInput/__tests__/__snapshots__/NumberInput.test.js.snap
  src/Input/TextInput/__tests__/__snapshots__/TextInput.test.js.snap
  src/Input/TextInput/index.js
Labels: bug, need review

#321 fix(Modal): fix size and mobile version of the component
  src/Modal/elements.js
  src/Modal/index.js
Labels: bug

#442 fix(Loader): use px instead of rem for Firefox support
  src/DatePicker/__tests__/__snapshots__/DatePicker.test.js.snap
  src/Loader/__tests__/__snapshots__/Loader.test.js.snap
  src/Loader/index.js
Labels: bug

#443 chore(deps): update babel monorepo
  package.json
  src/DatePicker/__tests__/__snapshots__/DatePicker.test.js.snap
  yarn.lock
Labels: dependencies update, need review, renovate

#446 chore(deps): update dependency eslint to v5.15.3
  package.json
  yarn.lock
Labels: dependencies update, need review, renovate

#455 feat(Tooltip): Change Tooltip to use the tippy library
  package.json
  src/Tooltip/README.md
  src/Tooltip/__stories__/Tooltip.stories.js
  src/Tooltip/__tests__/Tooltip.test.js
  src/Tooltip/__tests__/__snapshots__/Tooltip.test.js.snap
  src/Tooltip/elements.js
  src/Tooltip/helpers.js
  src/Tooltip/index.js
  yarn.lock
Labels: feature, need review

#458 fix(KpiChart): add possible design for mobile devices
  src/KpiChart/__stories__/KpiChart.stories.js
  src/KpiChart/__tests__/KpiChart.test.js
  src/KpiChart/elements.js
  src/KpiChart/index.js
Labels: enhancement

#459 fix(KpiBlock): improve UI when there is no variation to display
  src/KpiBlock/__tests__/__snapshots__/KpiBlock.test.js.snap
  src/KpiBlock/index.js
Labels: bug

#461 fix(Modal): add z-index to overlay to avoid elements overlapping it
  src/Modal/elements.js
Labels: enhancement

#460 feat(TabSwitcher): add new TabSwitcher component
  src/TabSwitcher/Pane/index.js
  src/TabSwitcher/Panes/elements.js
  src/TabSwitcher/Panes/index.js
  src/TabSwitcher/README.md
  src/TabSwitcher/Tab/elements.js
  src/TabSwitcher/Tab/index.js
  src/TabSwitcher/Tabs/elements.js
  src/TabSwitcher/Tabs/index.js
  src/TabSwitcher/__stories__/TabSwitcher.stories.js
  src/TabSwitcher/__tests__/TabSwitcher.test.js
  src/TabSwitcher/index.js
  src/index.js
Labels: feature, need review

#465 chore(deps): update babel monorepo to v7.4.3
  package.json
  yarn.lock
Labels: dependencies update, renovate

#466 chore(deps): update dependency @nivo/bar to v0.55.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#467 chore(deps): update dependency eslint to v5.16.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#468 chore(deps): update dependency polished to v3.2.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#470 chore(deps): update dependency react-testing-library to v6.1.2
  package.json
  yarn.lock
Labels: dependencies update, renovate

#469 chore(deps): update dependency popmotion to v8.6.8
  package.json
  yarn.lock
Labels: dependencies update, renovate

#471 chore(deps): update jest monorepo to v24.7.1
  package.json
  yarn.lock
Labels: dependencies update, renovate

#473 chore(deps): update react monorepo to v16.8.6
  package.json
  yarn.lock
Labels: dependencies update, renovate

#475 chore(deps): update dependency enzyme-adapter-react-16 to v1.12.1
  package.json
  yarn.lock
Labels: dependencies update, renovate

#474 chore(deps): update storybook monorepo to v5.0.6
  package.json
  yarn.lock
Labels: dependencies update, renovate

#476 fix(Storybook): install @storybook/theming to fix Error: Cannot find …
  package.json
  yarn.lock
Labels: bug

#477 chore(deps): pin dependency @storybook/theming to 5.0.6
  package.json
  yarn.lock
Labels: dependencies update, renovate

#464 fix(Button): remove default svg color on button
  src/Button/__stories__/Button.stories.js
  src/Button/__tests__/Button.test.js
  src/Button/__tests__/__snapshots__/Button.test.js.snap
  src/Button/__tests__/__snapshots__/helpers.test.js.snap
  src/Button/elements.js
  src/Button/helpers.js
  src/ButtonGroup/__tests__/__snapshots__/ButtonGroup.test.js.snap
  src/Counter/__tests__/__snapshots__/Increment.test.js.snap
  src/DatePicker/Header/__tests__/__snapshots__/Header.test.js.snap
  src/DatePicker/__tests__/__snapshots__/DatePicker.test.js.snap
  src/Form/__tests__/__snapshots__/Form.test.js.snap
Labels: bug, need review

#478 refactor(TabSwitcher): move TabSwitcher from class to function
  src/TabSwitcher/README.md
  src/TabSwitcher/__stories__/TabSwitcher.stories.js
  src/TabSwitcher/__tests__/TabSwitcher.test.js
  src/TabSwitcher/index.js
Labels: enhancement, need review

#480 fix(TabSwitcher): wrap pane in styled component
  src/TabSwitcher/Pane/elements.js
  src/TabSwitcher/Pane/index.js
Labels: bug

#479 fix(Dropdown): add z-index to menu
  src/Dropdown/elements.js
Labels: bug

#481 fix(TabSwitcher): update CSS
  src/TabSwitcher/Tab/elements.js
  src/TabSwitcher/Tabs/elements.js
  src/TabSwitcher/__tests__/TabSwitcher.test.js
Labels: enhancement

#483 fix(input): remove non handled @supports in jsdom and put 16px font-size
  src/Form/__tests__/__snapshots__/Form.test.js.snap
  src/Input/DatePickerInput/__tests__/__snapshots__/DatePickerInput.test.js.snap
  src/Input/NumberInput/__tests__/__snapshots__/NumberInput.test.js.snap
  src/Input/TextInput/__tests__/__snapshots__/TextInput.test.js.snap
  src/Input/TextInput/elements.js
Labels: bug

#484 fix(TabSwitcher): add guard for null children
  src/TabSwitcher/index.js
Labels: bug

#485 fix(Input): put font-size at 16px
  src/Form/__tests__/__snapshots__/Form.test.js.snap
  src/Input/DatePickerInput/__tests__/__snapshots__/DatePickerInput.test.js.snap
  src/Input/NumberInput/__tests__/__snapshots__/NumberInput.test.js.snap
  src/Input/TextInput/__tests__/__snapshots__/TextInput.test.js.snap
  src/Input/TextInput/elements.js
Labels: bug

#486 fix(Modal): use fixed position on modal container to avoid scrolling …
  src/Modal/elements.js
Labels: bug, need review

#487 fix(Tooltip): replace inline-block by inline-flex
  src/Tooltip/__tests__/__snapshots__/Tooltip.test.js.snap
  src/Tooltip/index.js
Labels: bug, need review

#488 chore(deps): update dependency prettier to v1.17.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#490 chore(deps): update dependency eslint-plugin-import to v2.17.2
  package.json
  yarn.lock
Labels: dependencies update, renovate

#495 feat(Table): update table component to suit our new design
  src/Icon/data.js
  src/KpiBlock/__tests__/__snapshots__/KpiBlock.test.js.snap
  src/Table/README.md
  src/Table/__stories__/Table.stories.js
  src/Table/__tests__/Table.test.js
  src/Table/__tests__/__snapshots__/Table.test.js.snap
  src/Table/elements.js
  src/Table/index.js
Labels: enhancement, feature, need review

#496 fix(TextInput): replace margin by padding inside input
  src/Form/__tests__/__snapshots__/Form.test.js.snap
  src/Input/DatePickerInput/__tests__/__snapshots__/DatePickerInput.test.js.snap
  src/Input/NumberInput/__tests__/__snapshots__/NumberInput.test.js.snap
  src/Input/TextInput/__tests__/__snapshots__/TextInput.test.js.snap
  src/Input/TextInput/elements.js
Labels: bug, need review

#497 fix: update color and KpiChart height
  src/Button/__tests__/__snapshots__/helpers.test.js.snap
  src/Button/helpers.js
  src/ButtonGroup/__tests__/__snapshots__/ButtonGroup.test.js.snap
  src/Counter/__tests__/__snapshots__/Increment.test.js.snap
  src/Dropdown/__tests__/__snapshots__/Dropdown.test.js.snap
  src/Dropdown/elements.js
  src/Input/Label/index.js
  src/Input/NumberInput/__tests__/__snapshots__/NumberInput.test.js.snap
  src/Input/TextInput/__tests__/__snapshots__/TextInput.test.js.snap
  src/KpiChart/Body/__tests__/__snapshots__/Body.test.js.snap
  src/KpiChart/Body/index.js
  src/KpiChart/__stories__/KpiChart.stories.js
  src/KpiChart/__tests__/KpiChart.test.js
  src/RadioButton/__tests__/__snapshots__/RadioButton.test.js.snap
  src/RadioButton/elements.js
  src/RadioGroup/__tests__/__snapshots__/RadioGroup.test.js.snap
  src/Table/elements.js
  src/Theme/palette.js
Labels: enhancement

#491 chore(deps): update storybook monorepo to v5.0.10
  package.json
  yarn.lock
Labels: dependencies update, renovate

#499 fix(Select): update value passed by parent and update resetValue
  src/Select/__stories__/Select.stories.js
  src/Select/__tests__/Select.test.js
  src/Select/index.js
Labels: bug, need review

#500 chore(deps): update dependency husky to v2
  package.json
  yarn.lock
Labels: dependencies update, renovate

#502 fix(TabSwitcher): display single Pane when there is only one
  src/TabSwitcher/Panes/index.js
Labels: bug

#493 chore(deps): update node.js to v11.14.0
  .circleci/config.yml
Labels: dependencies update, renovate

#503 chore(deps): update dependency eslint-config-prettier to v4.2.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#505 chore(deps): update babel monorepo to v7.4.4
  package.json
  yarn.lock
Labels: dependencies update, renovate

#506 chore(deps): update storybook monorepo to v5.0.11
  package.json
  yarn.lock
Labels: dependencies update, renovate

#507 fix(Table): never call handleSortingClick function if selected column…
  src/Table/__stories__/Table.stories.js
  src/Table/__tests__/Table.test.js
  src/Table/index.js
Labels: bug, need review

#508 chore(deps): update dependency jest-dom to v3.1.4
  package.json
  yarn.lock
Labels: dependencies update, renovate
