Repository tillersystems/Stardust, pull requests merged in 2019-06, with the labels that each got.

#544 fix: replace rem by px for Safari and Firefox support
  src/CheckBox/__tests__/__snapshots__/CheckBox.test.js.snap
  src/CheckBox/index.js
  src/Input/Status/__tests__/__snapshots__/status.test.js.snap
  src/Input/Status/index.js
  src/Input/TextInput/__tests__/__snapshots__/TextInput.test.js.snap
Labels: bug

#537 chore(deps): update dependency jest-dom to v3.4.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#538 chore(deps): update dependency eslint-plugin-import to v2.17.3
  package.json
  yarn.lock
Labels: dependencies update, renovate

#539 chore(deps): update dependency polished to v3.4.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#541 chore(deps): update dependency styled-components to v4.2.1
  package.json
  yarn.lock
Labels: dependencies update, renovate

#545 chore(deps): update "peerDependencies
  package.json
Labels: enhancement

#603 fix(Select): use prevent default method to cancel default action that…
  src/Select/index.js
Labels: bug, need review

#596 feat(Table): Add object support to hydrate row field
  src/Table/README.md
  src/Table/__stories__/Table.stories.js
  src/Table/__tests__/Table.test.js
  src/Table/index.js
Labels: feature, need review
