Repository tillersystems/Stardust, pull requests merged in 2019-05, with the labels that each got.

#509 chore(deps): update dependency popmotion to v8.6.9
  package.json
  yarn.lock
Labels: dependencies update, renovate

#510 chore(deps): update dependency husky to v2.2.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#512 chore(deps): update node.js to v11.15.0
  .circleci/config.yml
Labels: dependencies update, renovate

#515 chore(deps): update dependency conventional-changelog-cli to v2.0.21
  package.json
  yarn.lock
Labels: dependencies update, renovate

#516 chore(deps): update dependency polished to v3.3.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#517 chore(deps): update styled-component & react-pose to the latest version
  .storybook/config.js
  .storybook/styles.js
  package.json
  src/Avatar/__stories__/Avatar.stories.js
  src/Avatar/index.js
  src/Button/__tests__/__snapshots__/Button.test.js.snap
  src/Dropdown/index.js
  src/Input/DatePickerInput/index.js
  src/Input/TextInput/index.js
  src/Popover/index.js
  yarn.lock
Labels: enhancement, need review

#514 chore(deps): update jest monorepo to v24.8.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#511 chore(deps): update dependency eslint-plugin-react to v7.13.0
  package.json
  yarn.lock
Labels: dependencies update, need review, renovate

#518 fix(TabSwitcher): check for child displayName
  src/TabSwitcher/index.js
Labels: bug, need review

#519 fix(TabSwitcher): check that child is not null
  src/TabSwitcher/index.js
Labels: bug

#520 chore(deps): update dependency jest-dom to v3.2.1
  package.json
  yarn.lock
Labels: dependencies update, renovate

#522 chore(deps): update dependency jest-dom to v3.2.2
  package.json
  yarn.lock
Labels: dependencies update, renovate

#526 chore(deps): update dependency eslint-plugin-prettier to v3.1.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#523 chore(deps): update dependency popmotion to v8.6.10
  package.json
  yarn.lock
Labels: dependencies update, renovate

#527 chore(deps): update dependency babel-loader to v8.0.6
  package.json
  yarn.lock
Labels: dependencies update, renovate

#528 feat(TabSwicther): use context instead of react children map
  src/TabSwitcher/Pane/elements.js
  src/TabSwitcher/Pane/index.js
  src/TabSwitcher/Panes/elements.js
  src/TabSwitcher/Panes/index.js
  src/TabSwitcher/README.md
  src/TabSwitcher/Tab/elements.js
  src/TabSwitcher/Tab/index.js
  src/TabSwitcher/Tabs/elements.js
  src/TabSwitcher/Tabs/index.js
  src/TabSwitcher/__stories__/TabSwitcher.stories.js
  src/TabSwitcher/__tests__/TabSwitcher.test.js
  src/TabSwitcher/index.js
Labels: breaking change, enhancement, feature, need review

#529 chore(deps): update dependency prettier to v1.17.1
  package.json
  yarn.lock
Labels: dependencies update, renovate

#530 chore(deps): update dependency husky to v2.3.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#531 chore(deps): update dependency eslint-config-prettier to v4.3.0
  package.json
  yarn.lock
Labels: dependencies update, need review, renovate

#533 chore(deps): update dependency polished to v3.3.2
  package.json
  yarn.lock
Labels: dependencies update, renovate

#534 chore(deps): update dependency pretty-quick to v1.11.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#535 chore(deps): update babel monorepo to v7.4.5
  package.json
  yarn.lock
Labels: dependencies update, renovate

#536 feat(Icon): add new icons
  src/Icon/data.js
Labels: feature, need review
