Repository tillersystems/Stardust, pull requests merged in 2019-09, with the labels that each got.

#720 refactor(Counter): Rework the uncontrolled & controlled state
  src/Counter/README.md
  src/Counter/__stories__/Counter.stories.js
  src/Counter/__tests__/Increment.test.js
  src/Counter/index.js
Labels: enhancement, need review

#756 refactor(Notification): Rework of the component to stack notification
  src/Notification/Container.js
  src/Notification/NotificationsList.js
  src/Notification/README.md
  src/Notification/__stories__/Notifications.stories.js
  src/Notification/__tests__/__snapshots__/helpers.test.js.snap
  src/Notification/__tests__/__snapshots__/reducer.test.js.snap
  src/Notification/__tests__/helpers.test.js
  src/Notification/__tests__/provider.test.js
  src/Notification/__tests__/reducer.test.js
  src/Notification/elements.js
  src/Notification/helpers.js
  src/Notification/provider.js
  src/Notification/reducer.js
Labels: enhancement, need review

#759 refactor(Notification): Add key in addNotification options
  src/Notification/__stories__/Notifications.stories.js
  src/Notification/__tests__/provider.test.js
  src/Notification/provider.js
  src/Notification/reducer.js
Labels: enhancement

#727 feat(Table): Add scrollable behaviour to the Table component
  src/Table/README.md
  src/Table/__stories__/Table.stories.js
  src/Table/__tests__/Table.test.js
  src/Table/elements.js
  src/Table/index.js
  src/Theme/palette.js
Labels: feature

#766 feat(Notification/get/update): Retrieve and update a notification
  src/Notification/Container.js
  src/Notification/README.md
  src/Notification/__stories__/Notifications.stories.js
  src/Notification/__tests__/__snapshots__/reducer.test.js.snap
  src/Notification/__tests__/provider.test.js
  src/Notification/__tests__/reducer.test.js
  src/Notification/constants.js
  src/Notification/helpers.js
  src/Notification/provider.js
  src/Notification/reducer.js
Labels: enhancement, need review
