Repository tillersystems/Stardust, pull requests merged in 2019-02, with the labels that each got.

#378 feat(Form): Add new margin according to form design
  src/Form/Field/elements.js
  src/Form/Field/index.js
  src/Form/Group/elements.js
  src/Form/__tests__/__snapshots__/Form.test.js.snap
Labels: feature

#381 feat(Icon): add new shopping-bag icon
  src/Icon/data.js
Labels: enhancement

#382 chore(deps): update dependency eslint to v5.13.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#383 chore(deps): update dependency prettier to v1.16.4
  package.json
  yarn.lock
Labels: dependencies update, renovate

#384 chore(deps): update dependency eslint-plugin-jsx-a11y to v6.2.1
  package.json
  yarn.lock
Labels: dependencies update, renovate

#387 chore(deps): update dependency enzyme-adapter-react-16 to v1.9.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#388 chore(deps): update jest monorepo to v24.1.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#389 chore(deps): update dependency enzyme-adapter-react-16 to v1.9.1
  package.json
  yarn.lock
Labels: dependencies update, renovate

#390 chore(deps): update react monorepo to v16.8.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#391 chore(deps): update dependency jest-dom to v3.0.2
  package.json
  yarn.lock
Labels: dependencies update, renovate

#392 chore(deps): update dependency react-testing-library to v5.5.3
  package.json
  yarn.lock
Labels: dependencies update, renovate

#393 chore(deps): update react monorepo to v16.8.1
  package.json
  yarn.lock
Labels: dependencies update, renovate

#395 fix(*): fix Form and Select styles
  src/Form/Field/elements.js
  src/Form/Group/elements.js
  src/Form/__stories__/Form.stories.js
  src/Form/__tests__/__snapshots__/Form.test.js.snap
  src/Select/__tests__/__snapshots__/Select.test.js.snap
  src/Select/elements.js
  src/Select/index.js
Labels: bug

#396 chore(deps): update dependency react-testing-library to v5.5.4
  package.json
  yarn.lock
Labels: dependencies update, renovate

#397 chore(deps): update dependency jest-dom to v3.1.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#398 chore(deps): update dependency prop-types to v15.7.1
  package.json
  yarn.lock
Labels: dependencies update, renovate

#399 chore(deps): update dependency react-testing-library to v5.6.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#400 chore(deps): update dependency jest-dom to v3.1.1
  package.json
  yarn.lock
Labels: dependencies update, renovate

#402 feat(Date): add DatePickerInput component
  internal/jest/index.js
  src/Date/DatePicker/__tests__/DatePicker.test.js
  src/Date/DatePicker/index.js
  src/Input/DatePickerInput/README.md
  src/Input/DatePickerInput/__stories__/DatePickerInput.stories.js
  src/Input/DatePickerInput/__tests__/DatePickerInput.test.js
  src/Input/DatePickerInput/__tests__/__snapshots__/DatePickerInput.test.js.snap
  src/Input/DatePickerInput/elements.js
  src/Input/DatePickerInput/index.js
  src/Input/index.js
  src/index.js
Labels: feature

#401 chore(deps): update dependency react-testing-library to v5.8.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#404 chore(deps): update dependency prop-types to v15.7.2
  package.json
  yarn.lock
Labels: dependencies update, renovate

#406 chore(deps): update dependency conventional-changelog-cli to v2.0.12
  package.json
  yarn.lock
Labels: dependencies update, renovate

#405 chore(deps): update react monorepo to v16.8.2
  package.json
  yarn.lock
Labels: dependencies update, renovate

#407 chore(deps): update dependency jest-dom to v3.1.2
  package.json
  yarn.lock
Labels: dependencies update, renovate

#408 chore(deps): update dependency eslint to v5.14.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#409 chore(deps): update babel monorepo to v7.3.3
  package.json
  yarn.lock
Labels: dependencies update, renovate

#411 chore(deps): update dependency enzyme to v3.9.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#403 fix(Input/InputText): allow custom styles to override the style on focused input
  src/Form/__tests__/__snapshots__/Form.test.js.snap
  src/Input/DatePickerInput/__tests__/__snapshots__/DatePickerInput.test.js.snap
  src/Input/NumberInput/__tests__/__snapshots__/NumberInput.test.js.snap
  src/Input/TextInput/__stories__/TextInput.stories.js
  src/Input/TextInput/__tests__/TextInput.test.js
  src/Input/TextInput/__tests__/__snapshots__/TextInput.test.js.snap
  src/Input/TextInput/elements.js
  src/Input/TextInput/index.js
Labels: bug

#415 fix(Input): fix placeholder style
  package.json
  src/Form/__tests__/__snapshots__/Form.test.js.snap
  src/Input/DatePickerInput/__tests__/__snapshots__/DatePickerInput.test.js.snap
  src/Input/NumberInput/__tests__/__snapshots__/NumberInput.test.js.snap
  src/Input/TextInput/__tests__/__snapshots__/TextInput.test.js.snap
  src/Input/TextInput/elements.js
  yarn.lock
Labels: bug

#412 chore(deps): update storybook monorepo to v4.1.12
  package.json
  yarn.lock
Labels: dependencies update, renovate

#413 chore(deps): update dependency eslint to v5.14.1
  package.json
  yarn.lock
Labels: dependencies update, renovate

#414 chore(deps): update dependency react-testing-library to v5.9.0
  package.json
  yarn.lock
Labels: dependencies update, renovate

#417 chore(deps): update storybook monorepo to v4.1.13
  package.json
  yarn.lock
Labels: dependencies update, renovate

#416 feat(Variation): create Variation component
  src/Variation/README.md
  src/Variation/__stories__/Variation.stories.js
  src/Variation/__tests__/Variation.test.js
  src/Variation/__tests__/__snapshots__/Variation.test.js.snap
  src/Variation/index.js
  src/index.js
Labels: feature, need review

#418 fix(Date/*): update error state in DatePickerInput and date range limits in Weeks
  src/Date/DatePicker/__tests__/__snapshots__/DatePicker.test.js.snap
  src/Date/DateRangePicker/__tests__/__snapshots__/DateRangePicker.test.js.snap
  src/Date/Weeks/__tests__/__snapshots__/Week.test.js.snap
  src/Date/Weeks/index.js
  src/Input/DatePickerInput/__tests__/DatePickerInput.test.js
  src/Input/DatePickerInput/index.js
Labels: enhancement

#419 chore(deps): update dependency popmotion to v8.6.3
  package.json
  yarn.lock
Labels: dependencies update, renovate

#420 chore(deps): update react monorepo to v16.8.3
  package.json
  yarn.lock
Labels: dependencies update, renovate

#423 chore(deps): update dependency enzyme-adapter-react-16 to v1.10.0
  package.json
  yarn.lock
Labels: dependencies update, need review, renovate
