Repository tillersystems/Stardust, pull requests merged in 2019-08, with the labels that each got.

#675 fix(Select): update color of text
  src/DatePicker/__tests__/__snapshots__/DatePicker.test.js.snap
  src/Select/__tests__/__snapshots__/Select.test.js.snap
  src/Select/elements.js
Labels: need review

#678 fix(Card): Add export to Card
  src/index.js
Labels: bug, need review

#679 refactor(doc): update docs and stories from storybook
  .storybook/addons.js
  .storybook/config.js
  .storybook/webpack.config.js
  package.json
  src/Avatar/README.md
  src/Avatar/__stories__/Avatar.stories.js
  src/Avatar/index.js
  src/Button/README.md
  src/Button/__stories__/Button.stories.js
  src/Button/index.js
  src/ButtonGroup/README.md
  src/ButtonGroup/__stories__/ButtonGroup.stories.js
  src/ButtonGroup/index.js
  src/CheckBox/README.md
  src/CheckBox/__stories__/CheckBox.stories.js
  src/CheckBox/index.js
  src/Counter/README.md
  src/Counter/__stories__/Counter.stories.js
  src/Counter/index.js
  src/DatePicker/README.md
  src/DatePicker/__stories__/DatePicker.stories.js
  src/DatePicker/index.js
  src/Dropdown/README.md
  src/Dropdown/__stories__/Dropdown.stories.js
  src/Dropdown/index.js
  src/ScrollBox/elements.js
  src/Wrapper/index.js
  yarn.lock
Labels: enhancement

#682 feat(Icon): Add icon pie-chart & list
  src/Icon/data.js
Labels: feature

#706 fix(Card): makes overflowing content visible
  src/Card/__test__/__snapshots__/Card.test.js.snap
  src/Card/index.js
Labels: bug

#711 feat(Icon): add check-circle icon
  src/Icon/CheckCircle/index.js
  src/Icon/__tests__/Icon.test.js
  src/Icon/__tests__/__snapshots__/Icon.test.js.snap
  src/Icon/data.js
  src/Icon/index.js
Labels: feature, need review

#712 refactor(doc): update docs and stories from storybook
  src/Card/Header/index.js
  src/Card/README.md
  src/Card/__stories__/Card.stories.js
  src/Card/index.js
  src/Flag/README.md
  src/Flag/__stories__/Flag.stories.js
  src/Flag/index.js
  src/Form/Field/index.js
  src/Form/Group/index.js
  src/Form/README.md
  src/Form/__stories__/Form.stories.js
  src/Form/index.js
  src/Icon/README.md
  src/Icon/__stories__/Icon.stories.js
  src/Input/DatePickerInput/__stories__/DatePickerInput.stories.js
  src/Input/DatePickerInput/index.js
  src/Input/NumberInput/README.md
  src/Input/NumberInput/__stories__/NumberInput.stories.js
  src/Input/NumberInput/index.js
  src/Input/TextInput/README.md
  src/Input/TextInput/__stories__/TextInput.stories.js
  src/Input/TextInput/index.js
  src/KpiBlock/README.md
  src/KpiBlock/__stories__/KpiBlock.stories.js
  src/KpiBlock/index.js
  src/KpiChart/README.md
  src/KpiChart/__stories__/KpiChart.stories.js
  src/KpiChart/index.js
  src/Loader/README.md
  src/Loader/__stories__/Loader.stories.js
  src/Loader/index.js
  src/Logo/__stories__/Logo.stories.js
  src/Message/README.md
  src/Message/__stories__/Message.stories.js
  src/Message/__tests__/__snapshots__/Message.test.js.snap
  src/Message/helpers.js
  src/Message/index.js
  src/Modal/README.md
  src/Modal/__stories__/Modal.stories.js
  src/Modal/index.js
Labels: enhancement

#713 refactor(doc): update docs and stories from storybook
  src/Card/README.md
  src/Flag/README.md
  src/Form/README.md
  src/KpiChart/README.md
  src/Modal/README.md
  src/Notification/Container.js
  src/Notification/README.md
  src/Notification/__stories__/Notifications.stories.js
  src/Notification/provider.js
  src/RadioButton/README.md
  src/RadioButton/__stories__/RadioButton.stories.js
  src/RadioButton/index.js
  src/RadioGroup/README.md
  src/RadioGroup/__stories__/RadioGroup.stories.js
  src/RadioGroup/index.js
  src/Select/README.md
  src/Select/index.js
  src/TabSwitcher/Pane/index.js
  src/TabSwitcher/Panes/index.js
  src/TabSwitcher/README.md
  src/TabSwitcher/Tab/index.js
  src/TabSwitcher/__stories__/TabSwitcher.stories.js
  src/TabSwitcher/index.js
  src/Table/README.md
  src/Table/__stories__/Table.stories.js
  src/Table/index.js
  src/Tag/README.md
  src/Tag/__stories__/Tag.stories.js
  src/Tag/index.js
  src/ToggleButton/README.md
  src/ToggleButton/__stories__/ToggleButton.stories.js
  src/ToggleButton/__tests__/__snapshots__/ToggleButton.test.js.snap
  src/ToggleButton/index.js
  src/Tooltip/README.md
  src/Tooltip/__stories__/Tooltip.stories.js
  src/Tooltip/index.js
  src/Value/README.md
  src/Value/__stories__/Value.stories.js
  src/Value/index.js
  src/Variation/README.md
  src/Variation/__stories__/Variation.stories.js
  src/Variation/index.js
Labels: enhancement

#715 refactor(*): Remove Pin & Variation component from Stardust
  src/Pin/README.md
  src/Pin/__stories__/pin.stories.js
  src/Pin/__tests__/Pin.test.js
  src/Pin/__tests__/__snapshots__/Pin.test.js.snap
  src/Pin/index.js
  src/Variation/README.md
  src/Variation/__stories__/Variation.stories.js
  src/Variation/__tests__/Variation.test.js
  src/Variation/__tests__/__snapshots__/Variation.test.js.snap
  src/Variation/index.js
  src/index.js
Labels: feature, need review

#717 refactor(CheckBox): Rework the uncontrolled & controlled state
  src/CheckBox/README.md
  src/CheckBox/__stories__/CheckBox.stories.js
  src/CheckBox/__tests__/CheckBox.test.js
  src/CheckBox/__tests__/__snapshots__/CheckBox.test.js.snap
  src/CheckBox/elements.js
  src/CheckBox/index.js
Labels: enhancement, need review

#721 refactor(ToggleButton): Rework the uncontrolled & controlled state
  src/ToggleButton/README.md
  src/ToggleButton/__stories__/ToggleButton.stories.js
  src/ToggleButton/__tests__/ToggleButton.test.js
  src/ToggleButton/__tests__/__snapshots__/ToggleButton.test.js.snap
  src/ToggleButton/elements.js
  src/ToggleButton/index.js
Labels: enhancement, need review
