Repository tillersystems/Stardust, pull requests merged in 2019-12, with the labels that each got.

#912 feat(BreadCrumb): Add component to Stardust
  src/BreadCrumb/Item/index.js
  src/BreadCrumb/README.md
  src/BreadCrumb/__stories__/BreadCrumb.stories.js
  src/BreadCrumb/__tests__/BreadCrumb.test.js
  src/BreadCrumb/index.js
  src/index.js
Labels: feature, need review

#922 refactor(Table): replace selectable by onClick callback
  src/Table/TableBody.js
  src/Table/__stories__/Table.stories.js
  src/Table/__tests__/Table.test.js
  src/Table/elements.js
  src/Table/index.js
Labels: need review

#929 fix(Table): fix text/icon alignment
  src/Table/TableBody.js
  src/Table/elements.js
Labels: bug, need review

#942 feat(Table): controllable sort with onSortChange
  src/Table/README.md
  src/Table/TableBody.js
  src/Table/TableHeader.js
  src/Table/__stories__/Table.stories.js
  src/Table/__tests__/Table.test.js
  src/Table/__tests__/helpers.test.js
  src/Table/elements.js
  src/Table/helpers.js
  src/Table/index.js
  src/helpers/__tests__/compare.test.js
  src/helpers/compare.js
Labels: enhancement, feature, need review

#940 feat(Table): allow deep nested collapsible data
  src/Table/TableBody.js
  src/Table/__stories__/Table.stories.js
  src/Table/__tests__/Table.test.js
  src/Table/__tests__/helpers.test.js
  src/Table/elements.js
  src/Table/helpers.js
  src/Table/index.js
  src/helpers/__tests__/compare.test.js
  src/helpers/compare.js
Labels: enhancement, feature, need review

#943 feat(Navigation): Add component Navigation to project
  src/Navigation/README.md
  src/Navigation/__stories__/Navigation.stories.js
  src/Navigation/__tests__/Navigation.test.js
  src/Navigation/elements.js
  src/Navigation/index.js
Labels: feature, need review

#946 feat(Select): reintroduce displayValue props to customize Header
  src/Select/Header.js
  src/Select/__stories__/Select.stories.js
  src/Select/__tests__/Select.test.js
  src/Select/index.js
Labels: feature, need review
